// <auto-generated />
using System;
using DigitalTriageApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalTriageApp.Migrations
{
    [DbContext(typeof(MedicalTriageDbContext))]
    [Migration("20251110172353_UpdateMedicalDataModel")]
    partial class UpdateMedicalDataModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalTriageApp.Models.DoctorHospitalMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("DoctorId", "HospitalId", "IsActive")
                        .HasDatabaseName("IX_DoctorHospitalMembership_Doctor_Hospital_IsActive");

                    b.ToTable("DoctorHospitalMemberships");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.DoctorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DoctorProfiles");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.Domicile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Domiciles");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedByDoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByDoctorId");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.MedicalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("AuthorizedDoctorId")
                        .HasColumnType("int");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ChronicDiseases")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CurrentMedication")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("EstimatedWaitTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("FamilyHistory")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IncidentLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsConfidential")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastVisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LivingConditions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PersonalHistory")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PreliminaryDiagnosis")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TriageCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TriageLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizedDoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalDatas");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.MedicalFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MedicalDataId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MedicalDataId");

                    b.ToTable("MedicalFiles");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Citizenship")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cnp")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("DomicileId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nr")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PlaceOfBirthId")
                        .HasColumnType("int");

                    b.Property<int?>("PreferredHospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Serie")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("DomicileId");

                    b.HasIndex("PlaceOfBirthId");

                    b.HasIndex("PreferredHospitalId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.PatientIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientIssues");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.PlaceOfBirth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PlacesOfBirth");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.DoctorHospitalMembership", b =>
                {
                    b.HasOne("DigitalTriageApp.Models.DoctorProfile", "Doctor")
                        .WithMany("HospitalMemberships")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalTriageApp.Models.Hospital", "Hospital")
                        .WithMany("DoctorMemberships")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.DoctorProfile", b =>
                {
                    b.HasOne("DigitalTriageApp.Models.Patient", "User")
                        .WithOne("DoctorProfile")
                        .HasForeignKey("DigitalTriageApp.Models.DoctorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.Hospital", b =>
                {
                    b.HasOne("DigitalTriageApp.Models.DoctorProfile", "CreatedByDoctor")
                        .WithMany("CreatedHospitals")
                        .HasForeignKey("CreatedByDoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByDoctor");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.MedicalData", b =>
                {
                    b.HasOne("DigitalTriageApp.Models.DoctorProfile", "AuthorizedDoctor")
                        .WithMany("AuthorizedMedicalData")
                        .HasForeignKey("AuthorizedDoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DigitalTriageApp.Models.Patient", "Patient")
                        .WithMany("MedicalDatas")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorizedDoctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.MedicalFile", b =>
                {
                    b.HasOne("DigitalTriageApp.Models.MedicalData", "MedicalData")
                        .WithMany("Files")
                        .HasForeignKey("MedicalDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalData");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.Patient", b =>
                {
                    b.HasOne("DigitalTriageApp.Models.Domicile", "Domicile")
                        .WithMany()
                        .HasForeignKey("DomicileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigitalTriageApp.Models.PlaceOfBirth", "PlaceOfBirth")
                        .WithMany()
                        .HasForeignKey("PlaceOfBirthId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigitalTriageApp.Models.Hospital", "PreferredHospital")
                        .WithMany("AssignedPatients")
                        .HasForeignKey("PreferredHospitalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Domicile");

                    b.Navigation("PlaceOfBirth");

                    b.Navigation("PreferredHospital");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.PatientIssue", b =>
                {
                    b.HasOne("DigitalTriageApp.Models.Patient", "Patient")
                        .WithMany("Issues")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.DoctorProfile", b =>
                {
                    b.Navigation("AuthorizedMedicalData");

                    b.Navigation("CreatedHospitals");

                    b.Navigation("HospitalMemberships");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.Hospital", b =>
                {
                    b.Navigation("AssignedPatients");

                    b.Navigation("DoctorMemberships");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.MedicalData", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("DigitalTriageApp.Models.Patient", b =>
                {
                    b.Navigation("DoctorProfile");

                    b.Navigation("Issues");

                    b.Navigation("MedicalDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
